name: clippy

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.65.0
        with:
          components: clippy
      - name: lint
        run: cargo clippy --all-targets -- --deny warnings
